export const route = {
    home: '/',
    login: '/login',
    location: '/location',
    admin: '/admin',
    createSpot: '/spot',
    createFloorPlan: '/floor-plan',
    createLocation: '/createLocation',
    floorPlan: '/floorPlan',
    createReservation: '/create-reservation',
    calendar: '/calendar',
    user: '/user',
    updatePassword: '/user-update-password/:userId',
    updateProfilePicture: '/user-update-picture/:userId',
    register: '/register',
    notFound: '/*',
};
